version: '3.5'
services:

  kafka-iot-connect:
    container_name: kafka-iot-connect
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - kafka-iot-connect
    volumes:
      - ./:/root/kafka-iot-connect/
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 8081:8080
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    command: sleep 1000

networks:
  kafka-iot-connect:
    ipam:
      config:
        - subnet: 172.221.0.0/24
