// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAPIRequestResponse = "apiRequestResponse"

// APIRequestResponse mapped from table <apiRequestResponse>
type APIRequestResponse struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	APIRequestID int32     `gorm:"column:apiRequestId;not null" json:"apiRequestId"`
	StatusCode   int32     `gorm:"column:statusCode;not null" json:"statusCode"`
	Error        string    `gorm:"column:error;not null" json:"error"`
	ReceiveTime  time.Time `gorm:"column:receiveTime;not null" json:"receiveTime"`
	CreatedTime  time.Time `gorm:"column:createdTime;not null" json:"createdTime"`
	UpdatedTime  time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName APIRequestResponse's table name
func (*APIRequestResponse) TableName() string {
	return TableNameAPIRequestResponse
}
