// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAPIRequest = "apiRequest"

// APIRequest mapped from table <apiRequest>
type APIRequest struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           string    `gorm:"column:name;not null" json:"name"`
	Type           string    `gorm:"column:type;not null" json:"type"`
	Description    string    `gorm:"column:Description;not null" json:"Description"`
	APISchedulerID int32     `gorm:"column:apiSchedulerId;not null" json:"apiSchedulerId"`
	Method         string    `gorm:"column:method;not null" json:"method"`
	URL            string    `gorm:"column:url;not null" json:"url"`
	APIKey         string    `gorm:"column:apiKey;not null" json:"apiKey"`
	Order          int32     `gorm:"column:order;not null" json:"order"`
	CreatedTime    time.Time `gorm:"column:createdTime;not null" json:"createdTime"`
	UpdatedTime    time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName APIRequest's table name
func (*APIRequest) TableName() string {
	return TableNameAPIRequest
}
