// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBrickModelDatum = "BrickModelData"

// BrickModelDatum mapped from table <BrickModelData>
type BrickModelDatum struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BMSID      string `gorm:"column:BMS_id;not null" json:"BMS_id"`
	Alias      string `gorm:"column:alias;not null" json:"alias"`
	PointName  string `gorm:"column:PointName;not null" json:"PointName"`
	System     string `gorm:"column:System;not null" json:"System"`
	SubSystem  string `gorm:"column:SubSystem;not null" json:"SubSystem"`
	DeviceType string `gorm:"column:DeviceType;not null" json:"DeviceType"`
	DeviceName string `gorm:"column:DeviceName;not null" json:"DeviceName"`
	PointType  string `gorm:"column:PointType;not null" json:"PointType"`
	Location   string `gorm:"column:Location;not null" json:"Location"`
	Level      string `gorm:"column:Level;not null" json:"Level"`
	ClassType  string `gorm:"column:ClassType;not null" json:"ClassType"`
	Interval   string `gorm:"column:Interval;not null" json:"Interval"`
	Unit       string `gorm:"column:Unit;not null" json:"Unit"`
	Type       string `gorm:"column:Type;not null" json:"Type"`
	FileID     int32  `gorm:"column:FileId;not null" json:"FileId"`
}

// TableName BrickModelDatum's table name
func (*BrickModelDatum) TableName() string {
	return TableNameBrickModelDatum
}
