// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBrickModelFile = "BrickModelFile"

// BrickModelFile mapped from table <BrickModelFile>
type BrickModelFile struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	FileID       int32     `gorm:"column:FileId;not null" json:"FileId"`
	FileServerID int32     `gorm:"column:FileServerId;not null" json:"FileServerId"`
	ProjectID    string    `gorm:"column:projectId;not null" json:"projectId"`
	DataSourceID int32     `gorm:"column:dataSourceId;not null" json:"dataSourceId"`
	CreatedTime  time.Time `gorm:"column:createdTime" json:"createdTime"`
	UpdatedTime  time.Time `gorm:"column:updatedTime" json:"updatedTime"`
}

// TableName BrickModelFile's table name
func (*BrickModelFile) TableName() string {
	return TableNameBrickModelFile
}
