// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCalculationInflux = "calculationInflux"

// CalculationInflux mapped from table <calculationInflux>
type CalculationInflux struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name              string    `gorm:"column:name;not null" json:"name"`
	ProjectID         string    `gorm:"column:projectId;not null" json:"projectId"`
	DataSourceFromID  int32     `gorm:"column:dataSourceFromId;not null" json:"dataSourceFromId"`
	DataSourceToID    int32     `gorm:"column:dataSourceToId;not null" json:"dataSourceToId"`
	CalculationFileID int32     `gorm:"column:calculationFileId;not null" json:"calculationFileId"`
	ExeID             int32     `gorm:"column:exeId;not null" json:"exeId"`
	Status            int32     `gorm:"column:status;not null" json:"status"`
	FileID            int32     `gorm:"column:FileId;not null" json:"FileId"`
	Spec              string    `gorm:"column:spec;not null" json:"spec"`
	Interval          string    `gorm:"column:interval;not null" json:"interval"`
	StartTime         time.Time `gorm:"column:startTime" json:"startTime"`
	EndTime           time.Time `gorm:"column:endTime" json:"endTime"`
	CreatedTime       time.Time `gorm:"column:createdTime" json:"createdTime"`
	UpdatedTime       time.Time `gorm:"column:updatedTime" json:"updatedTime"`
}

// TableName CalculationInflux's table name
func (*CalculationInflux) TableName() string {
	return TableNameCalculationInflux
}
