// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDatasourceSecret = "datasourceSecret"

// DatasourceSecret mapped from table <datasourceSecret>
type DatasourceSecret struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type             string    `gorm:"column:type;not null" json:"type"`
	TypeID           int32     `gorm:"column:typeId;not null" json:"typeId"`
	DataSourceInfoID int32     `gorm:"column:dataSourceInfoId;not null" json:"dataSourceInfoId"`
	Status           int32     `gorm:"column:status;not null" json:"status"`
	Username         string    `gorm:"column:username;not null" json:"username"`
	Password         string    `gorm:"column:password;not null" json:"password"`
	CreatedTime      time.Time `gorm:"column:createdTime;not null" json:"createdTime"`
	UpdatedTime      time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName DatasourceSecret's table name
func (*DatasourceSecret) TableName() string {
	return TableNameDatasourceSecret
}
