// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEkuiperTransverseStream = "ekuiperTransverseStream"

// EkuiperTransverseStream mapped from table <ekuiperTransverseStream>
type EkuiperTransverseStream struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Type        string `gorm:"column:type;not null" json:"type"`
	StreamID    int32  `gorm:"column:streamId;not null" json:"streamId"`
	WaitingTime int32  `gorm:"column:waitingTime;not null" json:"waitingTime"`
	DefaultTime int32  `gorm:"column:defaultTime;not null" json:"defaultTime"`
}

// TableName EkuiperTransverseStream's table name
func (*EkuiperTransverseStream) TableName() string {
	return TableNameEkuiperTransverseStream
}
