// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEkuiperTransverse = "ekuiperTransverse"

// EkuiperTransverse mapped from table <ekuiperTransverse>
type EkuiperTransverse struct {
	ID             int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TransverseName string `gorm:"column:transverseName;not null" json:"transverseName"`
	Type           string `gorm:"column:type;not null" json:"type"`
	Status         int32  `gorm:"column:status;not null" json:"status"`
	IDColumn       string `gorm:"column:idColumn;not null" json:"idColumn"`
	ValueColumn    string `gorm:"column:valueColumn;not null" json:"valueColumn"`
	StreamID       int32  `gorm:"column:streamId;not null" json:"streamId"`
	SinkID         int32  `gorm:"column:sinkId;not null" json:"sinkId"`
}

// TableName EkuiperTransverse's table name
func (*EkuiperTransverse) TableName() string {
	return TableNameEkuiperTransverse
}
