// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEkuiperStream = "ekuiperStream"

// EkuiperStream mapped from table <ekuiperStream>
type EkuiperStream struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string `gorm:"column:name;not null" json:"name"`
	Type         string `gorm:"column:type;not null" json:"type"`
	TypeID       int32  `gorm:"column:typeId;not null" json:"typeId"`
	Topic        string `gorm:"column:topic;not null" json:"topic"`
	ProjectID    string `gorm:"column:projectId;not null" json:"projectId"`
	DataSourceID int32  `gorm:"column:dataSourceId;not null" json:"dataSourceId"`
	ClientID     int32  `gorm:"column:clientId;not null" json:"clientId"`
	Size         int32  `gorm:"column:size;not null" json:"size"`
}

// TableName EkuiperStream's table name
func (*EkuiperStream) TableName() string {
	return TableNameEkuiperStream
}
