// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEkuiperRuleNotification = "ekuiperRuleNotification"

// EkuiperRuleNotification mapped from table <ekuiperRuleNotification>
type EkuiperRuleNotification struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RuleID          int32     `gorm:"column:ruleId;not null" json:"ruleId"`
	CallbackID      int32     `gorm:"column:callbackId;not null" json:"callbackId"`
	Status          int32     `gorm:"column:status;not null" json:"status"`
	Type            string    `gorm:"column:type;not null" json:"type"`
	Response        string    `gorm:"column:response;not null" json:"response"`
	RecommendAction string    `gorm:"column:recommendAction;not null" json:"recommendAction"`
	CostSaving      int32     `gorm:"column:costSaving;not null" json:"costSaving"`
	MsgStatus       string    `gorm:"column:msgStatus;not null" json:"msgStatus"`
	Urgency         string    `gorm:"column:urgency;not null" json:"urgency"`
	Msgtype         string    `gorm:"column:msgtype;not null" json:"msgtype"`
	Reason          string    `gorm:"column:reason;not null" json:"reason"`
	ReceiveTime     time.Time `gorm:"column:receiveTime;not null" json:"receiveTime"`
}

// TableName EkuiperRuleNotification's table name
func (*EkuiperRuleNotification) TableName() string {
	return TableNameEkuiperRuleNotification
}
