// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEkuiperSql = "ekuiperSql"

// EkuiperSql mapped from table <ekuiperSql>
type EkuiperSql struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RuleID int32  `gorm:"column:ruleId;not null" json:"ruleId"`
	Sql    string `gorm:"column:sql" json:"sql"`
}

// TableName EkuiperSql's table name
func (*EkuiperSql) TableName() string {
	return TableNameEkuiperSql
}
