// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEkuiperCalculationSql = "ekuiperCalculationSql"

// EkuiperCalculationSql mapped from table <ekuiperCalculationSql>
type EkuiperCalculationSql struct {
	ID      int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RuleID  int32  `gorm:"column:ruleId;not null" json:"ruleId"`
	Sql     string `gorm:"column:sql;not null" json:"sql"`
	Aggre   int32  `gorm:"column:aggre;not null" json:"aggre"`
	NewSql  string `gorm:"column:newSql" json:"newSql"`
	Name    string `gorm:"column:name" json:"name"`
	Actions string `gorm:"column:actions;not null" json:"actions"`
}

// TableName EkuiperCalculationSql's table name
func (*EkuiperCalculationSql) TableName() string {
	return TableNameEkuiperCalculationSql
}
