// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEkuiperInterval = "ekuiperInterval"

// EkuiperInterval mapped from table <ekuiperInterval>
type EkuiperInterval struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID    string    `gorm:"column:projectId;not null" json:"projectId"`
	DataSourceID int32     `gorm:"column:dataSourceId;not null" json:"dataSourceId"`
	StreamID     int32     `gorm:"column:streamId;not null" json:"streamId"`
	Interval     int32     `gorm:"column:interval;not null" json:"interval"`
	Unit         string    `gorm:"column:unit;not null" json:"unit"`
	CreatedTime  time.Time `gorm:"column:createdTime" json:"createdTime"`
	UpdatedTime  time.Time `gorm:"column:updatedTime" json:"updatedTime"`
}

// TableName EkuiperInterval's table name
func (*EkuiperInterval) TableName() string {
	return TableNameEkuiperInterval
}
