// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEkuiperRuleEmail = "ekuiperRuleEmail"

// EkuiperRuleEmail mapped from table <ekuiperRuleEmail>
type EkuiperRuleEmail struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Type        string    `gorm:"column:type;not null" json:"type"`
	RuleID      int32     `gorm:"column:ruleId;not null" json:"ruleId"`
	SenderID    int32     `gorm:"column:senderId;not null" json:"senderId"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	ReceiverID  int32     `gorm:"column:receiverId;not null" json:"receiverId"`
	TemplateID  int32     `gorm:"column:templateId;not null" json:"templateId"`
	CallbackID  int32     `gorm:"column:callbackId;not null" json:"callbackId"`
	Spec        string    `gorm:"column:spec;not null" json:"spec"`
	StartTime   time.Time `gorm:"column:startTime;not null" json:"startTime"`
	EndTime     time.Time `gorm:"column:endTime;not null" json:"endTime"`
	CreatedTime time.Time `gorm:"column:createdTime" json:"createdTime"`
	UpdatedTime time.Time `gorm:"column:updatedTime" json:"updatedTime"`
}

// TableName EkuiperRuleEmail's table name
func (*EkuiperRuleEmail) TableName() string {
	return TableNameEkuiperRuleEmail
}
