// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEkuiperRuleMessage = "ekuiperRuleMessage"

// EkuiperRuleMessage mapped from table <ekuiperRuleMessage>
type EkuiperRuleMessage struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RuleID       int32  `gorm:"column:ruleId;not null" json:"ruleId"`
	RuleType     string `gorm:"column:ruleType;not null" json:"ruleType"`
	CallbackID   int32  `gorm:"column:callbackId;not null" json:"callbackId"`
	Types        string `gorm:"column:types;not null" json:"types"`
	Reason       string `gorm:"column:reason;not null" json:"reason"`
	Action       string `gorm:"column:action;not null" json:"action"`
	RuleName     string `gorm:"column:ruleName;not null" json:"ruleName"`
	Fdd          string `gorm:"column:fdd;not null" json:"fdd"`
	ProjectID    string `gorm:"column:projectId;not null" json:"projectId"`
	RuleDescribe string `gorm:"column:RuleDescribe;not null" json:"RuleDescribe"`
	Tags         string `gorm:"column:tags;not null" json:"tags"`
	CacheTime    string `gorm:"column:cacheTime;not null" json:"cacheTime"`
	Schedule     string `gorm:"column:schedule;not null" json:"schedule"`
	System       string `gorm:"column:system;not null" json:"system"`
	Equipment    string `gorm:"column:equipment;not null" json:"equipment"`
	Expression   string `gorm:"column:expression;not null" json:"expression"`
	Sensitivity  string `gorm:"column:sensitivity;not null" json:"sensitivity"`
	Urgency      int32  `gorm:"column:urgency;not null" json:"urgency"`
}

// TableName EkuiperRuleMessage's table name
func (*EkuiperRuleMessage) TableName() string {
	return TableNameEkuiperRuleMessage
}
