// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEkuiperRuleTemplate = "ekuiperRuleTemplate"

// EkuiperRuleTemplate mapped from table <ekuiperRuleTemplate>
type EkuiperRuleTemplate struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	DataSourceID int32     `gorm:"column:dataSourceId;not null" json:"dataSourceId"`
	RuleName     string    `gorm:"column:ruleName;not null" json:"ruleName"`
	RuleType     string    `gorm:"column:ruleType;not null" json:"ruleType"`
	RuleCategory string    `gorm:"column:ruleCategory;not null" json:"ruleCategory"`
	RawSql       string    `gorm:"column:rawSql;not null" json:"rawSql"`
	System       string    `gorm:"column:System;not null" json:"System"`
	SubSystem    string    `gorm:"column:SubSystem;not null" json:"SubSystem"`
	DeviceType   string    `gorm:"column:DeviceType;not null" json:"DeviceType"`
	DeviceName   string    `gorm:"column:DeviceName;not null" json:"DeviceName"`
	PointType    string    `gorm:"column:PointType;not null" json:"PointType"`
	Location     string    `gorm:"column:Location;not null" json:"Location"`
	Level        string    `gorm:"column:Level;not null" json:"Level"`
	Formula      string    `gorm:"column:formula;not null" json:"formula"`
	Variables    string    `gorm:"column:variables;not null" json:"variables"`
	CreatedTime  time.Time `gorm:"column:createdTime" json:"createdTime"`
	UpdatedTime  time.Time `gorm:"column:updatedTime" json:"updatedTime"`
}

// TableName EkuiperRuleTemplate's table name
func (*EkuiperRuleTemplate) TableName() string {
	return TableNameEkuiperRuleTemplate
}
