// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEkuiperRuleGraph = "ekuiperRuleGraph"

// EkuiperRuleGraph mapped from table <ekuiperRuleGraph>
type EkuiperRuleGraph struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name             string    `gorm:"column:name;not null" json:"name"`
	Type             string    `gorm:"column:type;not null" json:"type"`
	TypeID           int32     `gorm:"column:typeId;not null" json:"typeId"`
	DataSourceFromID int32     `gorm:"column:dataSourceFromId;not null" json:"dataSourceFromId"`
	DataSourceToID   int32     `gorm:"column:dataSourceToId;not null" json:"dataSourceToId"`
	StreamID         int32     `gorm:"column:streamId;not null" json:"streamId"`
	Status           int32     `gorm:"column:status;not null" json:"status"`
	TaggingFileID    int32     `gorm:"column:taggingFileId;not null" json:"taggingFileId"`
	Spec             string    `gorm:"column:spec;not null" json:"spec"`
	Interval         string    `gorm:"column:interval;not null" json:"interval"`
	StartTime        time.Time `gorm:"column:startTime;not null" json:"startTime"`
	EndTime          time.Time `gorm:"column:endTime;not null" json:"endTime"`
	CreatedTime      time.Time `gorm:"column:createdTime;not null" json:"createdTime"`
	UpdatedTime      time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName EkuiperRuleGraph's table name
func (*EkuiperRuleGraph) TableName() string {
	return TableNameEkuiperRuleGraph
}
