// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEkuiperServer = "ekuiperServer"

// EkuiperServer mapped from table <ekuiperServer>
type EkuiperServer struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Host       string `gorm:"column:host;not null" json:"host"`
	Port       int32  `gorm:"column:port;not null" json:"port"`
	ServerName string `gorm:"column:serverName;not null" json:"serverName"`
	Username   string `gorm:"column:username;not null" json:"username"`
	Password   string `gorm:"column:password;not null" json:"password"`
	TLSPath    string `gorm:"column:tlsPath;not null" json:"tlsPath"`
}

// TableName EkuiperServer's table name
func (*EkuiperServer) TableName() string {
	return TableNameEkuiperServer
}
