// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEkuiperRuleCallback = "ekuiperRuleCallback"

// EkuiperRuleCallback mapped from table <ekuiperRuleCallback>
type EkuiperRuleCallback struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Type        string `gorm:"column:type;not null" json:"type"`
	Status      int32  `gorm:"column:status;not null" json:"status"`
	Description string `gorm:"column:description;not null" json:"description"`
}

// TableName EkuiperRuleCallback's table name
func (*EkuiperRuleCallback) TableName() string {
	return TableNameEkuiperRuleCallback
}
