// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEkuiperClient = "ekuiperClient"

// EkuiperClient mapped from table <ekuiperClient>
type EkuiperClient struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ClientName string `gorm:"column:clientName;not null" json:"clientName"`
	ClientType string `gorm:"column:clientType;not null" json:"clientType"`
	ServerID   int32  `gorm:"column:serverId;not null" json:"serverId"`
}

// TableName EkuiperClient's table name
func (*EkuiperClient) TableName() string {
	return TableNameEkuiperClient
}
