// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmailResult = "emailResult"

// EmailResult mapped from table <emailResult>
type EmailResult struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	EmailID     int32     `gorm:"column:emailId;not null" json:"emailId"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	Response    string    `gorm:"column:response;not null" json:"response"`
	ReceiverID  int32     `gorm:"column:receiverId;not null" json:"receiverId"`
	ReceiveTime time.Time `gorm:"column:receiveTime;not null" json:"receiveTime"`
}

// TableName EmailResult's table name
func (*EmailResult) TableName() string {
	return TableNameEmailResult
}
