// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmailTemplate = "emailTemplate"

// EmailTemplate mapped from table <emailTemplate>
type EmailTemplate struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type        string    `gorm:"column:type;not null" json:"type"`
	TemplateKey string    `gorm:"column:templateKey;not null" json:"templateKey"`
	Body        string    `gorm:"column:body;not null" json:"body"`
	Subject     string    `gorm:"column:subject;not null" json:"subject"`
	CreatedTime time.Time `gorm:"column:createdTime" json:"createdTime"`
	UpdatedTime time.Time `gorm:"column:updatedTime" json:"updatedTime"`
}

// TableName EmailTemplate's table name
func (*EmailTemplate) TableName() string {
	return TableNameEmailTemplate
}
