// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmailClient = "emailClient"

// EmailClient mapped from table <emailClient>
type EmailClient struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username    string    `gorm:"column:username;not null" json:"username"`
	Password    string    `gorm:"column:password;not null" json:"password"`
	Email       string    `gorm:"column:email;not null" json:"email"`
	CreatedTime time.Time `gorm:"column:createdTime" json:"createdTime"`
	UpdatedTime time.Time `gorm:"column:updatedTime" json:"updatedTime"`
}

// TableName EmailClient's table name
func (*EmailClient) TableName() string {
	return TableNameEmailClient
}
