// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEmailTask = "emailTask"

// EmailTask mapped from table <emailTask>
type EmailTask struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TaskName   string `gorm:"column:taskName;not null" json:"taskName"`
	ProjectID  string `gorm:"column:projectId;not null" json:"projectId"`
	URL        string `gorm:"column:url;not null" json:"url"`
	TaskType   string `gorm:"column:taskType;not null" json:"taskType"`
	Desc       string `gorm:"column:desc;not null" json:"desc"`
	Status     int32  `gorm:"column:status;not null" json:"status"`
	Activated  int32  `gorm:"column:activated;not null" json:"activated"`
	DayBefore  int32  `gorm:"column:dayBefore;not null" json:"dayBefore"`
	ScheduleID int32  `gorm:"column:scheduleId;not null" json:"scheduleId"`
	UserID     int32  `gorm:"column:userId;not null" json:"userId"`
}

// TableName EmailTask's table name
func (*EmailTask) TableName() string {
	return TableNameEmailTask
}
