// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEtlTransform = "EtlTransform"

// EtlTransform mapped from table <EtlTransform>
type EtlTransform struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	ProjectID    string    `gorm:"column:projectId;not null" json:"projectId"`
	Type         string    `gorm:"column:type;not null" json:"type"`
	IDColumn     string    `gorm:"column:idColumn;not null" json:"idColumn"`
	ValueColumn  string    `gorm:"column:valueColumn;not null" json:"valueColumn"`
	StreamID     int32     `gorm:"column:streamId;not null" json:"streamId"`
	ClientID     int32     `gorm:"column:clientId;not null" json:"clientId"`
	DataSourceID int32     `gorm:"column:dataSourceId;not null" json:"dataSourceId"`
	TemplateID   int32     `gorm:"column:TemplateId;not null" json:"TemplateId"`
	Status       int32     `gorm:"column:status;not null" json:"status"`
	FileID       int32     `gorm:"column:FileId;not null" json:"FileId"`
	CreatedTime  time.Time `gorm:"column:createdTime" json:"createdTime"`
	UpdatedTime  time.Time `gorm:"column:updatedTime" json:"updatedTime"`
}

// TableName EtlTransform's table name
func (*EtlTransform) TableName() string {
	return TableNameEtlTransform
}
