// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFileServer = "FileServer"

// FileServer mapped from table <FileServer>
type FileServer struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Server      string    `gorm:"column:server;not null" json:"server"`
	ProjectName string    `gorm:"column:projectName;not null" json:"projectName"`
	Type        string    `gorm:"column:type;not null" json:"type"`
	Extension   string    `gorm:"column:extension;not null" json:"extension"`
	Path        string    `gorm:"column:path;not null" json:"path"`
	Size        int32     `gorm:"column:size;not null" json:"size"`
	CreatedID   string    `gorm:"column:createdId;not null" json:"createdId"`
	UpdatedID   string    `gorm:"column:updatedId;not null" json:"updatedId"`
	CreatedTime time.Time `gorm:"column:createdTime" json:"createdTime"`
	UpdatedTime time.Time `gorm:"column:updatedTime" json:"updatedTime"`
	ExpiryTime  time.Time `gorm:"column:expiryTime" json:"expiryTime"`
}

// TableName FileServer's table name
func (*FileServer) TableName() string {
	return TableNameFileServer
}
