// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFunctionUnit = "functionUnit"

// FunctionUnit mapped from table <functionUnit>
type FunctionUnit struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Alias       string    `gorm:"column:alias;not null" json:"alias"`
	CreatedTime time.Time `gorm:"column:createdTime" json:"createdTime"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	Unit        string    `gorm:"column:unit;not null" json:"unit"`
	UpdatedTime time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName FunctionUnit's table name
func (*FunctionUnit) TableName() string {
	return TableNameFunctionUnit
}
