// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFunctionFormula = "functionFormula"

// FunctionFormula mapped from table <functionFormula>
type FunctionFormula struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedTime time.Time `gorm:"column:createdTime" json:"createdTime"`
	EndTime     time.Time `gorm:"column:endTime" json:"endTime"`
	Formula     string    `gorm:"column:formula;not null" json:"formula"`
	FormulaType string    `gorm:"column:formulaType;not null" json:"formulaType"`
	StartTime   time.Time `gorm:"column:startTime" json:"startTime"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	UpdatedTime time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName FunctionFormula's table name
func (*FunctionFormula) TableName() string {
	return TableNameFunctionFormula
}
