// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFunctionConstant = "functionConstants"

// FunctionConstant mapped from table <functionConstants>
type FunctionConstant struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedTime time.Time `gorm:"column:createdTime" json:"createdTime"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Expression  string    `gorm:"column:expression;not null" json:"expression"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	UnitID      int32     `gorm:"column:unitId;not null" json:"unitId"`
	Value       float64   `gorm:"column:value;not null" json:"value"`
	UpdatedTime time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName FunctionConstant's table name
func (*FunctionConstant) TableName() string {
	return TableNameFunctionConstant
}
