// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFunctionRuleSqlAlias = "functionRuleSqlAlias"

// FunctionRuleSqlAlias mapped from table <functionRuleSqlAlias>
type FunctionRuleSqlAlias struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Alias       string    `gorm:"column:alias;not null" json:"alias"`
	CreatedTime time.Time `gorm:"column:createdTime" json:"createdTime"`
	Description string    `gorm:"column:description;not null" json:"description"`
	SqlType     string    `gorm:"column:sqlType" json:"sqlType"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	UnitID      int32     `gorm:"column:unitId;not null" json:"unitId"`
	UpdatedTime time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName FunctionRuleSqlAlias's table name
func (*FunctionRuleSqlAlias) TableName() string {
	return TableNameFunctionRuleSqlAlias
}
