// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFunctionEquip = "functionEquip"

// FunctionEquip mapped from table <functionEquip>
type FunctionEquip struct {
	ID            int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Alias         string `gorm:"column:alias;not null" json:"alias"`
	Capacity      string `gorm:"column:capacity;not null" json:"capacity"`
	Description   string `gorm:"column:description;not null" json:"description"`
	EquipmentName string `gorm:"column:equipmentName;not null" json:"equipmentName"`
	EquipmentType string `gorm:"column:equipmentType;not null" json:"equipmentType"`
	ProjectID     string `gorm:"column:projectId;not null" json:"projectId"`
}

// TableName FunctionEquip's table name
func (*FunctionEquip) TableName() string {
	return TableNameFunctionEquip
}
