// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFunctionUnitConvertion = "functionUnitConvertion"

// FunctionUnitConvertion mapped from table <functionUnitConvertion>
type FunctionUnitConvertion struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedTime time.Time `gorm:"column:createdTime" json:"createdTime"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Formula     string    `gorm:"column:formula;not null" json:"formula"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	UnitFromID  int32     `gorm:"column:unitFromId;not null" json:"unitFromId"`
	UnitToID    int32     `gorm:"column:unitToId;not null" json:"unitToId"`
	UpdatedTime time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName FunctionUnitConvertion's table name
func (*FunctionUnitConvertion) TableName() string {
	return TableNameFunctionUnitConvertion
}
