// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFunctionRuleSql = "functionRuleSql"

// FunctionRuleSql mapped from table <functionRuleSql>
type FunctionRuleSql struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RuleID       int32  `gorm:"column:ruleId;not null" json:"ruleId"`
	RuleSqlRawID int32  `gorm:"column:ruleSqlRawId;not null" json:"ruleSqlRawId"`
	Sql          string `gorm:"column:sql;not null" json:"sql"`
}

// TableName FunctionRuleSql's table name
func (*FunctionRuleSql) TableName() string {
	return TableNameFunctionRuleSql
}
