// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFunctionFormulaParam = "functionFormulaParams"

// FunctionFormulaParam mapped from table <functionFormulaParams>
type FunctionFormulaParam struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AggreFunc   string    `gorm:"column:aggreFunc;not null" json:"aggreFunc"`
	CreatedTime time.Time `gorm:"column:createdTime" json:"createdTime"`
	Expr        string    `gorm:"column:expr;not null" json:"expr"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	ParamType   string    `gorm:"column:paramType;not null" json:"paramType"`
	RuleSqlID   int32     `gorm:"column:ruleSqlId;not null" json:"ruleSqlId"`
	UnitID      int32     `gorm:"column:unitId;not null" json:"unitId"`
	UpdatedTime time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName FunctionFormulaParam's table name
func (*FunctionFormulaParam) TableName() string {
	return TableNameFunctionFormulaParam
}
