// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFunctionRuleSqlRaw = "functionRuleSqlRaw"

// FunctionRuleSqlRaw mapped from table <functionRuleSqlRaw>
type FunctionRuleSqlRaw struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Actions     string    `gorm:"column:actions;not null" json:"actions"`
	Aggre       int32     `gorm:"column:aggre;not null" json:"aggre"`
	ConditionID int32     `gorm:"column:conditionId;not null" json:"conditionId"`
	CreatedTime time.Time `gorm:"column:createdTime" json:"createdTime"`
	FormulaID   int32     `gorm:"column:formulaId;not null" json:"formulaId"`
	Name        string    `gorm:"column:name" json:"name"`
	NewSql      string    `gorm:"column:newSql" json:"newSql"`
	RuleAliasID int32     `gorm:"column:ruleAliasId;not null" json:"ruleAliasId"`
	Sql         string    `gorm:"column:sql;not null" json:"sql"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	UpdatedTime time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName FunctionRuleSqlRaw's table name
func (*FunctionRuleSqlRaw) TableName() string {
	return TableNameFunctionRuleSqlRaw
}
