// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFunctionModule = "functionModule"

// FunctionModule mapped from table <functionModule>
type FunctionModule struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Alias           string    `gorm:"column:alias;not null" json:"alias"`
	CalculationID   int32     `gorm:"column:calculationId;not null" json:"calculationId"`
	CalculationType string    `gorm:"column:calculationType;not null" json:"calculationType"`
	CreatedTime     time.Time `gorm:"column:createdTime" json:"createdTime"`
	Module          string    `gorm:"column:module;not null" json:"module"`
	Name            string    `gorm:"column:name;not null" json:"name"`
	PointTypeID     int32     `gorm:"column:pointTypeId;not null" json:"pointTypeId"`
	ProjectID       string    `gorm:"column:projectId;not null" json:"projectId"`
	RuleID          int32     `gorm:"column:ruleId;not null" json:"ruleId"`
	Status          int32     `gorm:"column:status;not null" json:"status"`
	UnitID          int32     `gorm:"column:unitId;not null" json:"unitId"`
	UpdatedTime     time.Time `gorm:"column:updatedTime" json:"updatedTime"`
	Version         string    `gorm:"column:version;not null" json:"version"`
}

// TableName FunctionModule's table name
func (*FunctionModule) TableName() string {
	return TableNameFunctionModule
}
