// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFunctionRuleSqlBm = "functionRuleSqlBms"

// FunctionRuleSqlBm mapped from table <functionRuleSqlBms>
type FunctionRuleSqlBm struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DataSourceID int32  `gorm:"column:dataSourceId;not null" json:"dataSourceId"`
	RuleID       int32  `gorm:"column:ruleId;not null" json:"ruleId"`
	RuleSqlID    int32  `gorm:"column:ruleSqlId;not null" json:"ruleSqlId"`
	Sql          string `gorm:"column:sql;not null" json:"sql"`
	Status       int32  `gorm:"column:status;not null" json:"status"`
}

// TableName FunctionRuleSqlBm's table name
func (*FunctionRuleSqlBm) TableName() string {
	return TableNameFunctionRuleSqlBm
}
