// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFunctionGroup = "functionGroup"

// FunctionGroup mapped from table <functionGroup>
type FunctionGroup struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Alias             string    `gorm:"column:alias;not null" json:"alias"`
	Category          string    `gorm:"column:category;not null" json:"category"`
	ChildAlias        string    `gorm:"column:childAlias;not null" json:"childAlias"`
	CreatedTime       time.Time `gorm:"column:createdTime" json:"createdTime"`
	DeviceType        string    `gorm:"column:deviceType;not null" json:"deviceType"`
	Discription       string    `gorm:"column:discription;not null" json:"discription"`
	Order             int32     `gorm:"column:order;not null" json:"order"`
	PointType         string    `gorm:"column:pointType;not null" json:"pointType"`
	SubCategory       string    `gorm:"column:subCategory;not null" json:"subCategory"`
	SubSubCategory    string    `gorm:"column:subSubCategory;not null" json:"subSubCategory"`
	SubSubSubCategory string    `gorm:"column:subSubSubCategory;not null" json:"subSubSubCategory"`
	Supplement        string    `gorm:"column:supplement;not null" json:"supplement"`
	UpdatedTime       time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
	Unit              string    `gorm:"column:unit;not null" json:"unit"`
	ValueType         string    `gorm:"column:valueType;not null" json:"valueType"`
	Version           string    `gorm:"column:version;not null" json:"version"`
}

// TableName FunctionGroup's table name
func (*FunctionGroup) TableName() string {
	return TableNameFunctionGroup
}
