// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKaflaStream = "kaflaStream"

// KaflaStream mapped from table <kaflaStream>
type KaflaStream struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Type        string `gorm:"column:type;not null" json:"type"`
	TypeID      int32  `gorm:"column:typeId;not null" json:"typeId"`
	StreamID    int32  `gorm:"column:streamId;not null" json:"streamId"`
	StreamType  string `gorm:"column:streamType;not null" json:"streamType"`
	WaitingTime int32  `gorm:"column:waitingTime;not null" json:"waitingTime"`
	Desc        string `gorm:"column:desc;not null" json:"desc"`
}

// TableName KaflaStream's table name
func (*KaflaStream) TableName() string {
	return TableNameKaflaStream
}
