// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMap = "map"

// Map mapped from table <map>
type Map struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type        string    `gorm:"column:type;not null" json:"type"`
	TypeID      int32     `gorm:"column:typeId;not null" json:"typeId"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	Value       float64   `gorm:"column:value" json:"value"`
	ValueStr    string    `gorm:"column:valueStr;not null" json:"valueStr"`
	Desc        string    `gorm:"column:desc;not null" json:"desc"`
	CreatedTime time.Time `gorm:"column:createdTime;not null" json:"createdTime"`
	UpdatedTime time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName Map's table name
func (*Map) TableName() string {
	return TableNameMap
}
