// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessageRecipient = "messageRecipient"

// MessageRecipient mapped from table <messageRecipient>
type MessageRecipient struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type        string    `gorm:"column:type;not null" json:"type"`
	TypeID      int32     `gorm:"column:typeId;not null" json:"typeId"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	ProjectID   string    `gorm:"column:projectId;not null" json:"projectId"`
	UserID      int32     `gorm:"column:userId;not null" json:"userId"`
	UserType    string    `gorm:"column:userType;not null" json:"userType"`
	UserUID     string    `gorm:"column:userUid;not null" json:"userUid"`
	CreatedTime time.Time `gorm:"column:createdTime;not null" json:"createdTime"`
	UpdatedTime time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName MessageRecipient's table name
func (*MessageRecipient) TableName() string {
	return TableNameMessageRecipient
}
