// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StreamID    int32     `gorm:"column:streamId;not null" json:"streamId"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	Type        string    `gorm:"column:type;not null" json:"type"`
	TypeID      int32     `gorm:"column:typeId;not null" json:"typeId"`
	Response    string    `gorm:"column:response;not null" json:"response"`
	ReceiveTime time.Time `gorm:"column:receiveTime;not null" json:"receiveTime"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
