// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessageLast = "messageLast"

// MessageLast mapped from table <messageLast>
type MessageLast struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StreamID    int32     `gorm:"column:streamId;not null" json:"streamId"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	Type        string    `gorm:"column:type;not null" json:"type"`
	TypeID      int32     `gorm:"column:typeId;not null" json:"typeId"`
	Response    string    `gorm:"column:response;not null" json:"response"`
	ReceiveTime time.Time `gorm:"column:receiveTime;not null" json:"receiveTime"`
}

// TableName MessageLast's table name
func (*MessageLast) TableName() string {
	return TableNameMessageLast
}
