// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNeo4jModel = "neo4jModel"

// Neo4jModel mapped from table <neo4jModel>
type Neo4jModel struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	FileID       int32     `gorm:"column:FileId;not null" json:"FileId"`
	DataSourceID int32     `gorm:"column:dataSourceId;not null" json:"dataSourceId"`
	CreatedID    string    `gorm:"column:createdId;not null" json:"createdId"`
	UpdatedID    string    `gorm:"column:updatedId;not null" json:"updatedId"`
	CreatedTime  time.Time `gorm:"column:createdTime" json:"createdTime"`
	UpdatedTime  time.Time `gorm:"column:updatedTime" json:"updatedTime"`
}

// TableName Neo4jModel's table name
func (*Neo4jModel) TableName() string {
	return TableNameNeo4jModel
}
