// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePlatformUser = "platformUser"

// PlatformUser mapped from table <platformUser>
type PlatformUser struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Status        int32     `gorm:"column:status;not null" json:"status"`
	CreatedTime   time.Time `gorm:"column:createdTime" json:"createdTime"`
	UpdatedTime   time.Time `gorm:"column:updatedTime" json:"updatedTime"`
	Email         string    `gorm:"column:email;not null" json:"email"`
	NickName      string    `gorm:"column:nickName;not null" json:"nickName"`
	PhoneNumber   string    `gorm:"column:phoneNumber;not null" json:"phoneNumber"`
	IdentityLabel string    `gorm:"column:identityLabel;not null" json:"identityLabel"`
	Picture       string    `gorm:"column:picture;not null" json:"picture"`
	Profile       string    `gorm:"column:profile;not null" json:"profile"`
	RoleID        string    `gorm:"column:roleId;not null" json:"roleId"`
	RoleName      string    `gorm:"column:roleName;not null" json:"roleName"`
	UserID        string    `gorm:"column:userId;not null" json:"userId"`
	UserName      string    `gorm:"column:userName;not null" json:"userName"`
	IsOwner       int32     `gorm:"column:isOwner;not null" json:"isOwner"`
	ProjectID     string    `gorm:"column:projectId;not null" json:"projectId"`
}

// TableName PlatformUser's table name
func (*PlatformUser) TableName() string {
	return TableNamePlatformUser
}
