// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePlatformProject = "platformProject"

// PlatformProject mapped from table <platformProject>
type PlatformProject struct {
	ID                  int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Status              int32     `gorm:"column:status;not null" json:"status"`
	CreatedTime         time.Time `gorm:"column:createdTime" json:"createdTime"`
	UpdatedTime         time.Time `gorm:"column:updatedTime" json:"updatedTime"`
	ProjectName         string    `gorm:"column:projectName;not null" json:"projectName"`
	ProjectID           string    `gorm:"column:projectId;not null" json:"projectId"`
	ProjectType         string    `gorm:"column:projectType;not null" json:"projectType"`
	TypeDesc            string    `gorm:"column:typeDesc;not null" json:"typeDesc"`
	Address             string    `gorm:"column:address;not null" json:"address"`
	Longitude           string    `gorm:"column:longitude;not null" json:"longitude"`
	Latitude            string    `gorm:"column:latitude;not null" json:"latitude"`
	ProjectModelAddress string    `gorm:"column:projectModelAddress;not null" json:"projectModelAddress"`
	Progress            string    `gorm:"column:progress;not null" json:"progress"`
	Country             string    `gorm:"column:country;not null" json:"country"`
	Province            string    `gorm:"column:province;not null" json:"province"`
	City                string    `gorm:"column:city;not null" json:"city"`
	Sort                string    `gorm:"column:sort;not null" json:"sort"`
	ProjectRoleDto      string    `gorm:"column:projectRoleDto;not null" json:"projectRoleDto"`
	Env                 string    `gorm:"column:env;not null" json:"env"`
	ServerDomain        string    `gorm:"column:serverDomain;not null" json:"serverDomain"`
}

// TableName PlatformProject's table name
func (*PlatformProject) TableName() string {
	return TableNamePlatformProject
}
