// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePredefinedModelSystem = "PredefinedModelSystem"

// PredefinedModelSystem mapped from table <PredefinedModelSystem>
type PredefinedModelSystem struct {
	ID            int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Class         string `gorm:"column:Class;not null" json:"Class"`
	System        string `gorm:"column:System;not null" json:"System"`
	Subsystem     string `gorm:"column:Subsystem;not null" json:"Subsystem"`
	EquipmentType string `gorm:"column:EquipmentType;not null" json:"EquipmentType"`
	FunctionType  string `gorm:"column:FunctionType;not null" json:"FunctionType"`
	Type          string `gorm:"column:Type;not null" json:"Type"`
	ModelID       int32  `gorm:"column:ModelId;not null" json:"ModelId"`
	FileID        int32  `gorm:"column:FileId;not null" json:"FileId"`
}

// TableName PredefinedModelSystem's table name
func (*PredefinedModelSystem) TableName() string {
	return TableNamePredefinedModelSystem
}
