// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePredefinedModelFile = "PredefinedModelFile"

// PredefinedModelFile mapped from table <PredefinedModelFile>
type PredefinedModelFile struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           string    `gorm:"column:name;not null" json:"name"`
	SystemFileID   int32     `gorm:"column:SystemFileId;not null" json:"SystemFileId"`
	LocationFileID int32     `gorm:"column:LocationFileId;not null" json:"LocationFileId"`
	ModelID        int32     `gorm:"column:ModelId;not null" json:"ModelId"`
	ProjectID      string    `gorm:"column:projectId;not null" json:"projectId"`
	DataSourceID   int32     `gorm:"column:dataSourceId;not null" json:"dataSourceId"`
	CreatedTime    time.Time `gorm:"column:createdTime" json:"createdTime"`
	UpdatedTime    time.Time `gorm:"column:updatedTime" json:"updatedTime"`
}

// TableName PredefinedModelFile's table name
func (*PredefinedModelFile) TableName() string {
	return TableNamePredefinedModelFile
}
