// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePredefinedModelLocation = "PredefinedModelLocation"

// PredefinedModelLocation mapped from table <PredefinedModelLocation>
type PredefinedModelLocation struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Class    string `gorm:"column:Class;not null" json:"Class"`
	Location string `gorm:"column:Location;not null" json:"Location"`
	Level    string `gorm:"column:Level;not null" json:"Level"`
	ModelID  int32  `gorm:"column:ModelId;not null" json:"ModelId"`
	FileID   int32  `gorm:"column:FileId;not null" json:"FileId"`
}

// TableName PredefinedModelLocation's table name
func (*PredefinedModelLocation) TableName() string {
	return TableNamePredefinedModelLocation
}
