// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePythonRuleSchedule = "pythonRuleSchedule"

// PythonRuleSchedule mapped from table <pythonRuleSchedule>
type PythonRuleSchedule struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RuleID          int32     `gorm:"column:ruleId;not null" json:"ruleId"`
	TimeseriesStart string    `gorm:"column:timeseriesStart;not null" json:"timeseriesStart"`
	TimeseriesEnd   string    `gorm:"column:timeseriesEnd;not null" json:"timeseriesEnd"`
	Spec            string    `gorm:"column:spec;not null" json:"spec"`
	Type            string    `gorm:"column:type;not null" json:"type"`
	TypeID          int32     `gorm:"column:typeId;not null" json:"typeId"`
	StartTime       time.Time `gorm:"column:startTime;not null" json:"startTime"`
	EndTime         time.Time `gorm:"column:endTime;not null" json:"endTime"`
	CreatedTime     time.Time `gorm:"column:createdTime;not null" json:"createdTime"`
	UpdatedTime     time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName PythonRuleSchedule's table name
func (*PythonRuleSchedule) TableName() string {
	return TableNamePythonRuleSchedule
}
