// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePythonRuleScheduler = "pythonRuleScheduler"

// PythonRuleScheduler mapped from table <pythonRuleScheduler>
type PythonRuleScheduler struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RuleName     string    `gorm:"column:ruleName;not null" json:"ruleName"`
	RuleID       int32     `gorm:"column:ruleId;not null" json:"ruleId"`
	RuleType     string    `gorm:"column:ruleType;not null" json:"ruleType"`
	RuleSubType  string    `gorm:"column:ruleSubType;not null" json:"ruleSubType"`
	CallbackID   int32     `gorm:"column:callbackId;not null" json:"callbackId"`
	MessageID    int32     `gorm:"column:messageId;not null" json:"messageId"`
	ScheduleID   int32     `gorm:"column:scheduleId;not null" json:"scheduleId"`
	DataSourceID int32     `gorm:"column:dataSourceId;not null" json:"dataSourceId"`
	SinkID       int32     `gorm:"column:sinkId;not null" json:"sinkId"`
	ProjectID    string    `gorm:"column:projectId;not null" json:"projectId"`
	Status       int32     `gorm:"column:Status;not null" json:"Status"`
	Activated    int32     `gorm:"column:activated;not null" json:"activated"`
	TriggerRule  string    `gorm:"column:triggerRule;not null" json:"triggerRule"`
	Retries      int32     `gorm:"column:retries;not null" json:"retries"`
	RetryPeriod  int32     `gorm:"column:retryPeriod;not null" json:"retryPeriod"`
	CreatedTime  time.Time `gorm:"column:createdTime;not null" json:"createdTime"`
	UpdatedTime  time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName PythonRuleScheduler's table name
func (*PythonRuleScheduler) TableName() string {
	return TableNamePythonRuleScheduler
}
