// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePythonRuleGraphEdge = "pythonRuleGraphEdge"

// PythonRuleGraphEdge mapped from table <pythonRuleGraphEdge>
type PythonRuleGraphEdge struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GraphID     int32     `gorm:"column:graphId;not null" json:"graphId"`
	RuleIDFrom  int32     `gorm:"column:ruleIdFrom;not null" json:"ruleIdFrom"`
	RuleIDTo    int32     `gorm:"column:ruleIdTo;not null;default:-1" json:"ruleIdTo"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	EdgeType    string    `gorm:"column:edgeType;not null" json:"edgeType"`
	CreatedTime time.Time `gorm:"column:createdTime;not null" json:"createdTime"`
	UpdatedTime time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName PythonRuleGraphEdge's table name
func (*PythonRuleGraphEdge) TableName() string {
	return TableNamePythonRuleGraphEdge
}
