// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePythonRuleGraphScheduler = "pythonRuleGraphScheduler"

// PythonRuleGraphScheduler mapped from table <pythonRuleGraphScheduler>
type PythonRuleGraphScheduler struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RuleName     string    `gorm:"column:ruleName;not null" json:"ruleName"`
	GraphID      int32     `gorm:"column:graphId;not null" json:"graphId"`
	ScheduleID   int32     `gorm:"column:scheduleId;not null" json:"scheduleId"`
	DataSourceID int32     `gorm:"column:dataSourceId;not null" json:"dataSourceId"`
	SinkID       int32     `gorm:"column:sinkId;not null" json:"sinkId"`
	ProjectID    string    `gorm:"column:projectId;not null" json:"projectId"`
	Status       int32     `gorm:"column:status;not null" json:"status"`
	Order        int32     `gorm:"column:order;not null" json:"order"`
	Activated    int32     `gorm:"column:activated;not null" json:"activated"`
	CreatedTime  time.Time `gorm:"column:createdTime;not null" json:"createdTime"`
	UpdatedTime  time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName PythonRuleGraphScheduler's table name
func (*PythonRuleGraphScheduler) TableName() string {
	return TableNamePythonRuleGraphScheduler
}
