// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePythonRuleFunction = "pythonRuleFunction"

// PythonRuleFunction mapped from table <pythonRuleFunction>
type PythonRuleFunction struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RuleName      string    `gorm:"column:ruleName;not null" json:"ruleName"`
	DisplayName   string    `gorm:"column:displayName;not null" json:"displayName"`
	System        string    `gorm:"column:system;not null" json:"system"`
	SubSystem     string    `gorm:"column:subSystem;not null" json:"subSystem"`
	EquipmentType string    `gorm:"column:equipmentType;not null" json:"equipmentType"`
	Type          string    `gorm:"column:type;not null" json:"type"`
	Description   string    `gorm:"column:description;not null" json:"description"`
	Fdd           string    `gorm:"column:fdd;not null" json:"fdd"`
	MessageID     int32     `gorm:"column:messageId;not null" json:"messageId"`
	ScheduleID    int32     `gorm:"column:scheduleId;not null" json:"scheduleId"`
	Tags          string    `gorm:"column:tags;not null" json:"tags"`
	CreatedTime   time.Time `gorm:"column:createdTime;not null" json:"createdTime"`
	UpdatedTime   time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName PythonRuleFunction's table name
func (*PythonRuleFunction) TableName() string {
	return TableNamePythonRuleFunction
}
