// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRabbitMQServer = "rabbitMQServer"

// RabbitMQServer mapped from table <rabbitMQServer>
type RabbitMQServer struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ServerName string `gorm:"column:serverName;not null" json:"serverName"`
	Host       string `gorm:"column:host;not null" json:"host"`
	Port       int32  `gorm:"column:port;not null" json:"port"`
	Username   string `gorm:"column:username;not null" json:"username"`
	Password   string `gorm:"column:password;not null" json:"password"`
	BrokerID   string `gorm:"column:brokerId;not null" json:"brokerId"`
	Region     string `gorm:"column:region;not null" json:"region"`
}

// TableName RabbitMQServer's table name
func (*RabbitMQServer) TableName() string {
	return TableNameRabbitMQServer
}
