// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRabbitMQClient = "rabbitMQClient"

// RabbitMQClient mapped from table <rabbitMQClient>
type RabbitMQClient struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ClientName string `gorm:"column:clientName;not null" json:"clientName"`
	ClientType string `gorm:"column:clientType;not null" json:"clientType"`
	ServerID   int32  `gorm:"column:serverId;not null" json:"serverId"`
	VHost      string `gorm:"column:vHost;not null" json:"vHost"`
}

// TableName RabbitMQClient's table name
func (*RabbitMQClient) TableName() string {
	return TableNameRabbitMQClient
}
