// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRabbitMQMessage = "rabbitMQMessage"

// RabbitMQMessage mapped from table <rabbitMQMessage>
type RabbitMQMessage struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Type        string    `gorm:"column:type;not null" json:"type"`
	ProjectID   string    `gorm:"column:projectId;not null" json:"projectId"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	ClientID    int32     `gorm:"column:clientId;not null" json:"clientId"`
	StreamID    int32     `gorm:"column:streamId;not null" json:"streamId"`
	SinkID      int32     `gorm:"column:sinkId;not null" json:"sinkId"`
	CallbackID  int32     `gorm:"column:callbackId;not null" json:"callbackId"`
	RClientID   int32     `gorm:"column:rClientId;not null" json:"rClientId"`
	QueueID     int32     `gorm:"column:queueId;not null" json:"queueId"`
	ExchangeID  int32     `gorm:"column:exchangeId;not null" json:"exchangeId"`
	RoutingKey  string    `gorm:"column:routingKey;not null" json:"routingKey"`
	Args        string    `gorm:"column:args;not null" json:"args"`
	Source      string    `gorm:"column:source;not null" json:"source"`
	CreatedTime time.Time `gorm:"column:createdTime;not null" json:"createdTime"`
	UpdatedTime time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName RabbitMQMessage's table name
func (*RabbitMQMessage) TableName() string {
	return TableNameRabbitMQMessage
}
