// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRabbitMQStream = "rabbitMQStream"

// RabbitMQStream mapped from table <rabbitMQStream>
type RabbitMQStream struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	StreamType  string    `gorm:"column:streamType;not null" json:"streamType"`
	Kind        string    `gorm:"column:kind;not null" json:"kind"`
	Durable     int32     `gorm:"column:durable;not null" json:"durable"`
	AutoDelete  int32     `gorm:"column:autoDelete;not null" json:"autoDelete"`
	Internal    int32     `gorm:"column:internal;not null" json:"internal"`
	Exclusive   int32     `gorm:"column:exclusive;not null" json:"exclusive"`
	NoWait      int32     `gorm:"column:noWait;not null" json:"noWait"`
	Desc        string    `gorm:"column:desc;not null" json:"desc"`
	Args        string    `gorm:"column:args;not null" json:"args"`
	CreatedTime time.Time `gorm:"column:createdTime;not null" json:"createdTime"`
	UpdatedTime time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName RabbitMQStream's table name
func (*RabbitMQStream) TableName() string {
	return TableNameRabbitMQStream
}
