// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRedisStream = "redisStream"

// RedisStream mapped from table <redisStream>
type RedisStream struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Key          string    `gorm:"column:key;not null" json:"key"`
	Field        string    `gorm:"column:field;not null" json:"field"`
	Size         int32     `gorm:"column:size;not null" json:"size"`
	Description  string    `gorm:"column:description;not null" json:"description"`
	DataSourceID int32     `gorm:"column:dataSourceId;not null" json:"dataSourceId"`
	Status       int32     `gorm:"column:status;not null" json:"status"`
	Type         string    `gorm:"column:type;not null" json:"type"`
	TypeID       int32     `gorm:"column:typeId;not null" json:"typeId"`
	StartTime    string    `gorm:"column:startTime;not null" json:"startTime"`
	EndTime      string    `gorm:"column:endTime;not null" json:"endTime"`
	CreatedTime  time.Time `gorm:"column:createdTime;not null" json:"createdTime"`
	UpdatedTime  time.Time `gorm:"column:updatedTime;not null" json:"updatedTime"`
}

// TableName RedisStream's table name
func (*RedisStream) TableName() string {
	return TableNameRedisStream
}
