// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaggingInflux = "taggingInflux"

// TaggingInflux mapped from table <taggingInflux>
type TaggingInflux struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name             string    `gorm:"column:name;not null" json:"name"`
	ProjectID        string    `gorm:"column:projectId;not null" json:"projectId"`
	DataSourceFromID int32     `gorm:"column:dataSourceFromId;not null" json:"dataSourceFromId"`
	DataSourceToID   int32     `gorm:"column:dataSourceToId;not null" json:"dataSourceToId"`
	TaggingFileID    int32     `gorm:"column:taggingFileId;not null" json:"taggingFileId"`
	Status           int32     `gorm:"column:status;not null" json:"status"`
	Type             string    `gorm:"column:type;not null" json:"type"`
	Spec             string    `gorm:"column:spec;not null" json:"spec"`
	Interval         string    `gorm:"column:interval;not null" json:"interval"`
	StartTime        time.Time `gorm:"column:startTime" json:"startTime"`
	EndTime          time.Time `gorm:"column:endTime" json:"endTime"`
	CreatedTime      time.Time `gorm:"column:createdTime" json:"createdTime"`
	UpdatedTime      time.Time `gorm:"column:updatedTime" json:"updatedTime"`
}

// TableName TaggingInflux's table name
func (*TaggingInflux) TableName() string {
	return TableNameTaggingInflux
}
